triggers:
  - name: app_launch_flag
    description: Запуск в МП
    type: flag
    event_name: app_launch

  - name: add_to_cart_counts
    description: Добавление в корзину
    type: metric
    event_name: add_to_cart
    where:
      in:
        action: [add_to_cart]

  - name: mainpage_click_flag
    description: Клик по главной
    type: flag
    event_name: mainpage_click
    where:
      eq:
        action: click

  - name: mainpage_view_counts
    description: Просмотры главной
    type: metrics
    event_name: *
    where:
      eq:
        page: mainpage

  - name: click_counts
    description: Любые клики
    type: metric
    event_name: *
    where:
      eq:
        action: click
